stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - aston
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
test-job:
  stage: test
  tags:
    - aston
  script:
    - echo "This is a test job to check the GitLab Runner."
    - uname -a
    - whoami
