---
- name: Install and configure GitLab Runner
  hosts: local
  become: yes
  vars:
    docker_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  vars_files:
    - ~/.ansible/group_vars/all.yml
  tasks:
    - name: Debug gitlab_url
      debug:
        msg: "gitlab_url is {{ gitlab_url }}"

    - name: Debug gitlab_registration_token
      debug:
        msg: "gitlab_registration_token is {{ gitlab_registration_token }}"

    - name: Debug gitlab_runner_name
      debug:
        msg: "gitlab_runner_name is {{ gitlab_runner_name }}"

    - name: Install required packages
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "{{ docker_repo }}"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Add user to Docker group
      user:
        name: gitlab-runner
        groups: docker
        append: yes

    - name: Download GitLab Runner binary
      get_url:
        url: "https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64"
        dest: /usr/local/bin/gitlab-runner
        mode: '0755'

    - name: Create gitlab-runner user
      user:
        name: gitlab-runner
        createhome: yes
        shell: /bin/bash

    - name: Check if GitLab Runner service file exists
      stat:
        path: /etc/systemd/system/gitlab-runner.service
      register: gitlab_runner_service_file

    - name: Install GitLab Runner service
      command: /usr/local/bin/gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner
      when: not gitlab_runner_service_file.stat.exists

    - name: Start GitLab Runner service
      service:
        name: gitlab-runner
        state: started
        enabled: yes

    - name: Register GitLab Runner
      environment:
        GITLAB_URL: "{{ gitlab_url }}"
        REGISTRATION_TOKEN: "{{ gitlab_registration_token }}"
      command: >
        /usr/local/bin/gitlab-runner register --non-interactive
        --url "{{ gitlab_url }}"
        --registration-token "{{ gitlab_registration_token }}"
        --executor docker
        --description "{{ gitlab_runner_name }}"
        --tag-list "docker, shell, shared, linux"
        --docker-image "docker:latest"
        --run-untagged
        --locked="false"
      args:
        creates: /etc/gitlab-runner/config.toml
